<h1 style="text-align:center; font-size:160%; font-family:verdana;color:#F44A79;"><em>Date 21-06-2021</em></h1>

<h1 style="text-align:center; font-size:360%; font-family:verdana;color:#4A3E76;"><em>Slicing Rows and Columns with iloc</em></h1>

In [1]:
import pandas as pd

In [2]:
summer_olmypic_data_csv=pd.read_csv('summer_data.csv',index_col='Athlete')
summer_olmypic_data_csv

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [3]:
summer_olmypic_data_csv.iloc[0:10,7]

Athlete
HAJOS, Alfred              Gold
HERSCHMANN, Otto         Silver
DRIVAS, Dimitrios        Bronze
MALOKINIS, Ioannis         Gold
CHASAPIS, Spiridon       Silver
CHOROPHAS, Efstathios    Bronze
HAJOS, Alfred              Gold
ANDREOU, Joannis         Silver
CHOROPHAS, Efstathios    Bronze
NEUMANN, Paul              Gold
Name: Medal, dtype: object

In [4]:
summer_olmypic_data_csv.iloc[0:10,[2,-3,-1]]

                          Sport Gender   Medal
Athlete
HAJOS, Alfred          Aquatics    Men    Gold
HERSCHMANN, Otto       Aquatics    Men  Silver
DRIVAS, Dimitrios      Aquatics    Men  Bronze
MALOKINIS, Ioannis     Aquatics    Men    Gold
CHASAPIS, Spiridon     Aquatics    Men  Silver
CHOROPHAS, Efstathios  Aquatics    Men  Bronze
HAJOS, Alfred          Aquatics    Men    Gold
ANDREOU, Joannis       Aquatics    Men  Silver
CHOROPHAS, Efstathios  Aquatics    Men  Bronze
NEUMANN, Paul          Aquatics    Men    Gold