<h1 style="text-align:center; font-size:160%; font-family:verdana;color:#F44A79;"><em>Date 21-06-2021</em></h1>

<h1 style="text-align:center; font-size:360%; font-family:verdana;color:#4A3E76;"><em>Zero based and Negative Indexing</em></h1>

In [1]:
import pandas as pd

In [2]:
summer_olmypic_data_csv=pd.read_csv('summer_data.csv')
summer_olmypic_data_csv

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [3]:
summer_olmypic_data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31165 entries, 0 to 31164
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        31165 non-null  int64
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Athlete     31165 non-null  object
 5   Country     31161 non-null  object
 6   Gender      31165 non-null  object
 7   Event       31165 non-null  object
 8   Medal       31165 non-null  object
dtypes: int64(1), object(8)
memory usage: 2.1+ MB

In [4]:
summer_olmypic_data_csv.describe()

               Year
count  31165.000000
mean    1970.482785
std       33.158416
min     1896.000000
25%     1948.000000
50%     1980.000000
75%     2000.000000
max     2012.000000

In [5]:
summer_olmypic_data_csv=pd.read_csv('summer_data.csv',index_col='Athlete')
pd.options.display.min_rows=50
summer_olmypic_data_csv

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
"GMELIN, Charles",1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
"JAMISON, Herbert",1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
"GOLEMIS, Dimitrios",1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
...,...,...,...,...,...,...,...,...
"KAYAALP, Riza",2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
"SORYAN REIHANPOUR, Hamid Mohammad",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
"BAYRAMOV, Rovshan",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
"MODOS, Peter",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
"SEMENOV, Mingiyan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
"NOROOZI, Omid Haji",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
"LASHKHI, Revaz",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
"KURAMAGOMEDOV, Zaur",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
"MATSUMOTO, Ryutaro",2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
"KIM, Hyeonwoo",2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
"LORINCZ, Tamas",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
"GUENOT, Steeve",2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
"TSKHADAIA, Manuchar",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
"VLASOV, Roman",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
"JULFALAKYAN, Arsen",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [6]:
summer_olmypic_data_csv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31165 entries, HAJOS, Alfred to LIDBERG, Jimmy
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        31165 non-null  int64
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Country     31161 non-null  object
 5   Gender      31165 non-null  object
 6   Event       31165 non-null  object
 7   Medal       31165 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.1+ MB

In [7]:
summer_olmypic_data_csv.describe()

               Year
count  31165.000000
mean    1970.482785
std       33.158416
min     1896.000000
25%     1948.000000
50%     1980.000000
75%     2000.000000
max     2012.000000

---
# +ve index positioning with iloc

In [8]:
summer_olmypic_data_csv.iloc[0]

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Country                  HUN
Gender                   Men
Event         100M Freestyle
Medal                   Gold
Name: HAJOS, Alfred, dtype: object

In [9]:
summer_olmypic_data_csv.iloc[1]

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Country                  AUT
Gender                   Men
Event         100M Freestyle
Medal                 Silver
Name: HERSCHMANN, Otto, dtype: object

In [10]:
type(summer_olmypic_data_csv.iloc[1])

pandas.core.series.Series

In [11]:
summer_olmypic_data_csv.iloc[[3,5,9,13]]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold

In [12]:
summer_olmypic_data_csv.iloc[3:13]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze

---
# -ve index positioning with iloc

In [14]:
summer_olmypic_data_csv.iloc[-1]

Year                         2012
City                       London
Sport                   Wrestling
Discipline    Wrestling Freestyle
Country                       SWE
Gender                        Men
Event                    Wg 96 KG
Medal                      Bronze
Name: LIDBERG, Jimmy, dtype: object

In [13]:
summer_olmypic_data_csv.iloc[-9:-5]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze